import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),dir='../../tools/detection-capability/';
const lob=require(dir+'lob-analysis.js'),gof=require(dir+'lod-gof-contract.js'),lod=require(dir+'lod-browser.js'),loq=require(dir+'loq-contract.js'),project=require(dir+'project-file-contract.js');
const values=Array.from({length:60},(_,i)=>i+1),original=values.slice();
const b=lob.analyze({values,alpha:.05,unit:'ng/mL'});assert.equal(b.status,'calculated');assert.equal(b.groupLoB,57.5);assert.deepEqual(values,original);
assert.equal(lob.analyze({values,alpha:.1,unit:'ng/mL'}).status,'blocked');
assert.equal(lob.analyze({values:values.slice(1),alpha:.05,unit:'ng/mL'}).status,'blocked');
assert.equal(lod.validate({c:[1,2],n:[20,20],k:[4,16],target:.95}),true);
assert.equal(lod.validate({c:[1,1],n:[20,20],k:[4,16],target:.95}),false);
assert.equal(lod.validate({c:[1,,3],n:[20,20,20],k:[4,10,16],target:.95}),false);
const q={c:[1,2,3,4],n:[20,20,20,20]},e={status:'candidate',residualDF:2,pearson:2,deviance:4,expectedPositive:[1,8,12,19],expectedNegative:[19,12,8,1],diagnostics:[]};
const f={gofStatus:'calculated',pearsonP:String(Math.exp(-1)),devianceP:String(Math.exp(-2)),pearsonPerDF:'1'};
const g=gof.fromFields(f,e,q);assert(gof.valid(g,e,q));assert.deepEqual(g.smallExpectedRows,[1,4]);assert.equal(g.method.ciDispersion,1);assert.equal(g.method.assessment,'review_required');
for(const mutation of [{pearsonP:1.1},{pearsonP:NaN},{pearsonPerDF:2},{method:{...g.method,ciDispersion:2}},{smallExpectedRows:[]}])assert.equal(gof.valid({...g,...mutation},e,q),false);
assert.throws(()=>gof.fromFields({...f,pearsonP:''},e,q),/invalid_response/);
assert(gof.fromFields({...f,devianceP:'1'},{...e,deviance:-1e-14},q).warnings.includes('DEVIANCE_ROUNDOFF'));
assert.throws(()=>gof.fromFields(f,{...e,deviance:-.1},q),/invalid_response/);
const held=gof.fromFields({gofStatus:'held'},{...e,residualDF:0,expectedPositive:[4,16],expectedNegative:[16,4]}, {c:[1,2],n:[20,20]});assert.equal(held.pearsonP,null);assert.equal(held.pearsonPerDF,null);assert(held.warnings.includes('NO_RESIDUAL_DF'));
assert.deepEqual(gof.fromFields({}, {status:'separation'},{}),gof.empty());
const ql={unit:'ng/mL',limitFraction:.2,samples:[{sampleName:'A',referenceValue:10,referenceSource:'Synthetic',values:[9,10,11]}]};
assert.deepEqual(loq.validate(ql),[]);const l=loq.assemble(ql,[{n:3,mean:10,sd:1,bias:0,te:2,teFraction:.2}],{rVersion:'4.6.0',statsVersion:'4.6.0'});assert.equal(l.samples[0].criterionStatus,'met');assert.equal(l.groupLoQCandidate,null);assert(l.candidateReasons.includes('CANDIDATE_COUNT_HELD'));
assert.equal(typeof project,'object');
const raw=k=>({key:k,unit:'ng/mL',setting:k==='lob'?'10':'',group:'Synthetic',reference:'',dataKind:'합성',rows:[],blank:k==='lob'?values.join('\n'):'',samples:[]});
const saved={format:'mdc-minimal-project',version:1,savedAt:'2026-10-04T00:00:00Z',activeModule:'lob',modules:Object.fromEntries(project.keys.map(k=>[k,{raw:raw(k),revision:0,source:null,history:[]}])),archivedResults:{lod:{version:'lod-point-2',method:{applicationVersion:'0.9.1-beta.2'},modelDoseCandidate:19},confirmation:null,lob:null,loq:null}};
const restored=project.parse(JSON.stringify(saved));assert.deepEqual(restored,saved);assert.equal(restored.modules.lob.raw.setting,'10');assert.equal(restored.archivedResults.lod.method.applicationVersion,'0.9.1-beta.2');
saved.archivedResults.lod={gof:g,version:'lod-point-3'};assert.deepEqual(project.parse(JSON.stringify(saved)).archivedResults.lod.gof,g);
assert.throws(()=>project.parse(JSON.stringify({...saved,version:2})),/지원하지 않는 버전/);
console.log('PASS: LoBDQ independent LoB anchor, input boundaries, GOF held/range/tamper contract, LoQ boundary/candidate safeguards. Synthetic only.');
