import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {analyze,outputText,position,lengthSummary,VERSION} from '../../tools/sequence/core.mjs';
// Synthetic DOM adapter executes the actual app module; browser layout is checked separately.
class Element{constructor(){this.value='';this.checked=false;this.disabled=false;this.textContent='';this.events={};this.attrs={};this.children=[];}addEventListener(k,f){this.events[k]=f;}setAttribute(k,v){this.attrs[k]=v;}append(...xs){this.children.push(...xs);}replaceChildren(...xs){this.children=xs;}focus(){}showModal(){this.open=true;}close(){this.open=false;this.events.close?.();}}
const elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id);};get('sequence-output-mode').value='DNA';get('sequence-name').value='sequence_1';get('sequence-width').value='60';let copied;
const source=(await readFile(new URL('../../tools/sequence/app.mjs',import.meta.url),'utf8')).replace(/^import .*;\r?\n/,'').replace('export const TOOL_VERSION','const TOOL_VERSION');
vm.runInNewContext(source,{analyze,outputText,position,lengthSummary,VERSION,document:{getElementById:get,createElement:()=>new Element(),createDocumentFragment:()=>new Element()},navigator:{clipboard:{writeText:async value=>{copied=value;}}}});
function input(value){get('sequence-input').value=value;get('sequence-input').events.input();}function change(id,value){get(id).value=value;get(id).events.change();}function click(id){return get(id).events.click();}
input('>single description\natGc');assert.equal(get('sequence-fasta-on').checked,false);assert.equal(get('sequence-output').value,'>single description\natGc\n');assert.equal(get('sequence-copy').textContent,'FASTA 복사');assert.equal(get('sequence-copy').disabled,false);await click('sequence-copy');assert.equal(copied,'>single description\natGc\n');
click('sequence-upper');assert.equal(get('sequence-output').value,'>single description\nATGC\n');assert.equal(get('sequence-upper').attrs['aria-pressed'],'true');assert.equal(get('sequence-upper').textContent,'대문자 적용 중');click('sequence-upper');assert.equal(get('sequence-output').value,'>single description\natGc\n');assert.equal(get('sequence-upper').attrs['aria-pressed'],'false');assert.equal(get('sequence-input').value,'>single description\natGc');
get('sequence-reverse').checked=true;get('sequence-complement').checked=true;change('sequence-output-mode','RNA');assert.equal(get('sequence-output').value,'>single description\ngCau\n');assert(get('sequence-result-note').textContent.includes('5′→3′'));get('sequence-reverse').checked=false;get('sequence-reverse').events.change();assert(get('sequence-result-note').textContent.includes('주의: 이 FASTA 결과는 3′→5′'));
get('sequence-width').value='2.5';get('sequence-width').events.input();assert.equal(get('sequence-output').value,'');assert.equal(get('sequence-copy').disabled,true);get('sequence-width').value='60';get('sequence-width').events.input();
get('sequence-complement').checked=false;change('sequence-output-mode','DNA');input('>a\nAT--GC');assert(get('sequence-warnings').textContent.includes('gap'));assert.equal(get('sequence-output').value,'>a\nATGC\n');input('>a\nATGC\n>b\nCGTA');assert.equal(get('sequence-output').value,'>a\nATGC\n>b\nCGTA\n');input('ATGC');assert.equal(get('sequence-output').value,'ATGC');get('sequence-fasta-on').checked=true;get('sequence-fasta-on').events.change();assert.equal(get('sequence-output').value,'>sequence_1\nATGC\n');
input('AT?GC');assert.equal(get('sequence-output').value,'');assert.equal(get('sequence-copy').disabled,true);click('sequence-upper');click('sequence-clear');assert.equal(get('sequence-input').value,'');assert.equal(get('sequence-output').value,'');assert.equal(get('sequence-upper').attrs['aria-pressed'],'false');
console.log('PASS: actual app single/multi FASTA and copy, case toggle/raw retention, RNA/direction, gap, width/error/clear contract. Synthetic DOM, no native clipboard/browser layout claim.');
