import assert from 'node:assert/strict';
import {calculate} from '../../tools/oligo-mix/core.mjs';
import {excelClipboard,nextComponentName,safeText,TOOL_VERSION} from '../../tools/oligo-mix/clipboard.mjs';
const r=calculate({reaction:'25',mix:'5',count:'10',rows:[{name:'F1',target:'.2',stock:'10'},{name:'R1',target:'.1',stock:'10'},{name:'P1',target:'.1',stock:'10'}]});
const p=excelClipboard(r);
assert.equal(p.rows.length,7);assert(p.rows.every(row=>row.length===10));
assert.deepEqual(p.rows[0].slice(0,4),['Final Volume','','25','µL']);
assert.equal(p.rows[1][2],'10');assert.equal(p.rows[1][4],'Final conc / amount');assert.equal(p.rows[1][6],'stock conc');
assert.deepEqual(p.rows[2],['','TE pH8.0','40','µL','-','','-','','4','µL']);
assert.deepEqual(p.rows[3],['1','F1','5','µL','0.2','µM','10','µM','0.5','µL']);
assert.equal(p.rows[4][1],'R1');assert.equal(p.rows[5][1],'P1');
assert.equal(p.rows[6][2],'50');assert.equal(p.rows[6][8],'5');
assert.equal(p.text.split('\r\n').length,7);assert(p.text.split('\r\n').every(row=>row.split('\t').length===10));
assert(p.html.includes("font-family:'맑은 고딕','Malgun Gothic',sans-serif;font-size:9pt;"));
assert(!p.html.includes('#ccd5df')&&!p.html.includes('border:1px'));
assert(p.html.includes('colspan="6"')&&p.html.includes('colspan="4"'));
assert(p.html.includes('도구 '+TOOL_VERSION)&&p.html.includes('알고리즘 0.5.0'));
for(const prefix of ['=','+','-','@'])assert(safeText('  '+prefix+'Synthetic').startsWith("'"));
assert.equal(safeText('A\tB\nC'),'A B C');
const evil=excelClipboard(calculate({reaction:'25',mix:'5',count:'10',rows:[{name:'  =Synthetic<script>&"',target:'.2',stock:'10'}]}));
assert(!evil.html.includes('<script>'));assert(evil.html.includes('&lt;script&gt;')&&evil.text.includes("'=Synthetic"));
assert.deepEqual(nextComponentName('F',{F:1}),{name:'F2',count:2});
assert.deepEqual(nextComponentName('F',{F:1},['F2']),{name:'F3',count:3});
assert.deepEqual(nextComponentName('Plasmid',{}),{name:'Plasmid1',count:1});
assert.throws(()=>nextComponentName('unknown',{}));
console.log('PASS: dynamic 7x10 layout, TE/batch/per-reaction positions, no reserved rows/borders, numeric values, Malgun Gothic9pt HTML, merges, HTML/formula safety and per-type naming.');

const precise=calculate({reaction:'1',mix:'1',count:'1',rows:[{name:'Precision',target:'0.123456789012345',stock:'1'}]});
const preciseCopy=excelClipboard(precise);assert.equal(preciseCopy.rows[3][8],'0.123456789012');assert.equal(preciseCopy.rows[3][4],'0.123456789012');assert.notEqual(precise.rows[0].perReaction,Number(preciseCopy.rows[3][8]),'Clipboard rounding does not replace the calculation value');
assert(preciseCopy.text.includes('0.123456789012'));assert(preciseCopy.html.includes('0.123456789012'));
console.log('PASS: explicit12 significant-digit clipboard values; calculation values retained.');
