import assert from 'node:assert/strict';
import {calculate,proposePreparation,remainingTE,adjusted,checkPipette} from '../../tools/oligo-mix/core.mjs';
import {parseOligoPaste} from '../../tools/oligo-mix/paste.mjs';
import {excelClipboard} from '../../tools/oligo-mix/clipboard.mjs';
const input={reaction:'25',mix:'5',count:'10',rows:[{name:'Synthetic',target:'.4538',stock:'100'}]},r=calculate(input);
assert.equal(r.rows[0].batch,1.1345);
assert.deepEqual(proposePreparation(r,'.01'),{volumes:['1.13'],te:'48.87'});
assert.deepEqual(proposePreparation(r,'.1'),{volumes:['1.1'],te:'48.9'});
assert.equal(r.rows[0].batch,1.1345);assert.equal(input.rows[0].target,'.4538');
const tie=calculate({...input,rows:[{name:'Tie',target:'.454',stock:'100'}]});assert.equal(proposePreparation(tie,'.01').volumes[0],'1.14');
assert.equal(remainingTE(r,['1.2']),'48.8');assert.throws(()=>remainingTE(r,['50.000000000000001']));
assert.throws(()=>proposePreparation(r,'0'));assert.throws(()=>proposePreparation(r,'NaN'));
const overshoot=calculate({reaction:'1',mix:'.3',count:'1',rows:[{name:'A',target:'.15',stock:'1'},{name:'B',target:'.15',stock:'1'}]});assert.throws(()=>proposePreparation(overshoot,'.1'),/초과/);
const tiny=calculate({...input,rows:[{name:'Small',target:'.001',stock:'100'}]});assert.deepEqual(proposePreparation(tiny,'.1'),{volumes:['0'],te:'50'});assert.equal(adjusted(tiny,['0'],'50').rows[0].deviationPercent,-100);
const outcome=adjusted(r,['1.13'],'48.87');assert.equal(outcome.total,50);assert(Math.abs(outcome.rows[0].achieved-.452)<1e-15);
assert.equal(checkPipette('1.13',{step:'.01',min:'1.2',max:'10'}).valid,false);
assert.equal(checkPipette('1.13',{step:'.01',min:'',max:''}).valid,true);assert.throws(()=>checkPipette('1',{step:'.1',min:'1',max:''}));
assert.equal(checkPipette(remainingTE(r,['.3']),{step:'.3',min:'',max:''}).valid,false);
const many=calculate({...input,rows:Array.from({length:100},(_,i)=>({name:'Row '+i,target:'.001',stock:'100'}))});assert.equal(many.rows.length,100);const clip=excelClipboard(many);assert.equal(clip.rows.length,104);assert.equal(clip.rows.at(-1)[0],'Total');assert(!clip.html.includes('#ccd5df'));
const excluded=calculate({...input,rows:[{name:'Out',target:'',stock:'0',enabled:false},...input.rows]});assert.equal(excluded.rows[0].sourceIndex,2);assert.equal(excelClipboard(excluded).rows[3][0],'2');
const pasted=parseOligoPaste('A\t.2\t100\nB\t.1\t\n\n');assert.equal(pasted.rows.length,2);assert.equal(pasted.defaults,1);assert.equal(pasted.rows[1].stock,'100');
assert.equal(parseOligoPaste('이름\t최종 농도\tStock\nA\t.2\t10',{header:true,type:'R'}).rows[0].type,'R');
assert.deepEqual(parseOligoPaste('A\t.1\t100\nA\t.2\t100').duplicates,['A']);
for(const text of ['A\t.1','A\t.1\t100\textra','A\t=1+1\t100','A\t.1\t0','\t.1\t100','A\t.1\t100\nB\tinvalid\t100'])assert.throws(()=>parseOligoPaste(text));
assert.throws(()=>parseOligoPaste('A\t.1\t100',{type:'Plasmid'}));assert.throws(()=>parseOligoPaste('x'.repeat(2*1024*1024+1)));
console.log('PASS: exact total-volume nearest/half-up proposals, TE balance, manual edits, impossible rounding/zero component, range checks, 100 rows/dynamic borderless copy/source numbers, 3-column parsing/defaults/atomic errors.');
