import {parseInput,preflight,VERSION,formatDG,isWarning,parseCutoff,filteredPairs,textReport,excelReport,KINDS,LABELS,polyLines} from './core.mjs';
const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let worker=null,snapshot=null,input=null,targets=new Set(),generation=0,kind='self',selected=null,listPage=0,structurePage=0,currentFilters=null,visible=[];
let copyEpoch=0;const copyTimers=new Map();
function clearCopyNotices(){copyEpoch++;for(const id of ['copy-all','copy-pair']){clearTimeout(copyTimers.get(id));const note=$(id+'-notice');note.textContent='';note.dataset.state='';}}
function copyNotice(id,message,state,temporary=false){clearTimeout(copyTimers.get(id));const note=$(id+'-notice');note.textContent=message;note.dataset.state=state;if(temporary)copyTimers.set(id,setTimeout(()=>{note.textContent='';note.dataset.state='';},3000));}
const helpers={idt:'IDT 기준 로컬 계산. 기본 표시는 ΔG ≤ −9 또는 3′ 말단 연속 3 bp이며 분석 후 조절합니다.',thermo:'Thermo optimal 3 원본 검출·도식만 표시합니다. cut-off·ΔG 경고·3′ 보충 검출은 적용하지 않습니다.'};
const num=n=>Number.isSafeInteger(n)?n.toLocaleString():'지원 상한 초과';
function clearResults(message){clearCopyNotices();generation++;worker?.terminate();worker=null;snapshot=null;selected=null;$('results').hidden=true;$('error').hidden=true;$('cancel').hidden=true;$('analyze').disabled=false;$('start').disabled=false;for(const id of ['copy-all','copy-pair','save'])$(id).disabled=true;$('copy-status').textContent='';if(message)$('status').textContent=message;}
function invalidate(message='입력 또는 방식을 변경했습니다. 계산량을 다시 확인하세요.'){clearResults(message);input=null;targets.clear();$('preflight').hidden=true;$('mode-help').textContent=helpers[$('mode').value];}
function showError(message){clearResults('분석하지 못했습니다. 입력과 분석 범위를 확인하세요.');$('error').textContent=message;$('error').hidden=false;if(input)renderPlan();}
const selectedRecords=()=>input.records.filter(r=>targets.has(r.name));
const options=()=>Object.fromEntries(KINDS.map(k=>[k,$('include-'+k).checked]));
function renderPlan(){if(!input)return;const records=selectedRecords(),mode=$('mode').value,plan=preflight(records,mode,options());$('include-poly').disabled=mode==='thermo';$('include-poly').closest('label').hidden=mode==='thermo';$('exclude-poly').hidden=mode==='thermo'||!$('include-poly').checked;$('plan-details').replaceChildren(el('p',`선택 ${records.length}/${input.records.length}종 · 실제 서열 ${num(plan.totalVariants)}개`));for(const k of KINDS){if(mode==='thermo'&&k==='poly')continue;const m=plan.modules[k],p=el('p',`${LABELS[k]}: ${m.selected?'계산 선택':'제외'} · ${k==='poly'?'3분자 조합':'실제 서열쌍'} ${num(m.pairs)}개`,m.selected&&m.reasons.length?'warning':m.selected&&m.warning?'attention':'');if(m.selected&&m.reasons.length)p.append(el('span',' · '+m.reasons.join(' / ')));$('plan-details').append(p);}$('start').disabled=plan.blocked;$('start').textContent=plan.warning&&!plan.blocked?'경고 확인 후 선택 범위 분석':'선택 범위 분석';$('plan-message').className=plan.blocked?'warning':plan.warning?'attention':'note';$('plan-message').textContent=plan.blocked?'지원 상한을 넘는 항목 또는 대상을 줄이세요. '+plan.reasons.join(' '):plan.warning?'계산량이 많습니다. 경고를 확인하고 진행하거나 Polydimer 제외·대상 primer 축소를 선택하세요. Polydimer는 실행 시간과 추정 보관량을 확인하며 탐색합니다.':'선택한 분석 범위가 지원 예산 안에 있습니다.';}
function renderTargets(){$('targets').replaceChildren();for(const r of input.records){const label=el('label'),check=el('input');check.type='checkbox';check.checked=targets.has(r.name);check.addEventListener('change',()=>{check.checked?targets.add(r.name):targets.delete(r.name);clearResults('대상 변경: 계산량을 다시 확인했습니다.');renderPlan();});label.append(check,document.createTextNode(`${r.name} · ${r.sequence.length} nt · 실제 서열 ${num(r.variants)}개`));$('targets').append(label);}}
$('sequences').addEventListener('input',()=>invalidate());$('mode').addEventListener('change',()=>invalidate());
$('clear').addEventListener('click',()=>{$('sequences').value='';invalidate('서열을 입력하고 계산량을 확인하세요.');$('sequences').focus();});
$('example').addEventListener('click',()=>{$('sequences').value='Primer_F  ATGACCTGATCGTAGCTAGC\nPrimer_R  GCTAGCTACGATCAGGTCAT\nMixed  GCNGC\nNo_self  AAAAAAAAAAAA';invalidate('합성 예제를 불러왔습니다. 계산량을 확인하세요.');});
$('analysis-form').addEventListener('submit',event=>{event.preventDefault();invalidate();try{input=parseInput($('sequences').value);targets=new Set(input.records.map(r=>r.name));renderTargets();$('preflight').hidden=false;renderPlan();$('status').textContent='계산할 항목과 대상을 확인한 뒤 선택 범위 분석을 누르세요.';}catch(error){showError(error.message);}});
for(const k of KINDS)$('include-'+k).addEventListener('change',()=>{clearResults('분석 항목 변경: 계산량을 다시 확인했습니다.');renderPlan();});
$('exclude-poly').addEventListener('click',()=>{$('include-poly').checked=false;clearResults('Polydimer를 제외했습니다. Self/Hetero 계산량을 확인하세요.');renderPlan();});
$('select-all').addEventListener('click',()=>{targets=new Set(input.records.map(r=>r.name));clearResults('전체 대상을 선택했습니다.');renderTargets();renderPlan();});
$('cancel').addEventListener('click',()=>{clearResults('계산을 취소했습니다. 입력과 선택 범위를 유지했습니다.');renderPlan();});
$('start').addEventListener('click',()=>{if(!input)return;const records=selectedRecords(),mode=$('mode').value,opts=options(),plan=preflight(records,mode,opts);if(plan.blocked){renderPlan();return;}clearResults('분석 중입니다. 취소하거나 입력·범위를 변경하면 계산을 중단합니다.');const token=generation,excluded=input.records.filter(r=>!targets.has(r.name)).map(r=>r.name);$('start').disabled=true;$('cancel').hidden=false;try{worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});}catch{showError('계산을 시작하지 못했습니다. 로컬 서버 주소로 접속하세요.');return;}worker.onmessage=({data})=>{if(token!==generation)return;if(data.progress){$('status').textContent=`${LABELS[data.progress.kind]} 계산 중 · ${num(data.progress.done)}${data.progress.total?'/'+num(data.progress.total):''}조합 확인${data.progress.elapsedMs!==undefined?' · 경과 '+Math.floor(data.progress.elapsedMs/1000)+'초':''} · 취소할 수 있습니다.`;return;}worker.terminate();worker=null;$('cancel').hidden=true;renderPlan();if(data.error){showError(data.error);return;}snapshot={...data.result,records,mode,excluded};$('results').hidden=false;$('idt-filters').hidden=mode==='thermo';$('tab-poly').hidden=mode==='thermo';$('result-method').textContent=mode==='thermo'?'Thermo optimal 3 · 원본 검출/정렬 표시':'IDT 기준 로컬 계산 · ΔG25 · Polydimer는 별도 구간 점수 후보';$('scope-status').textContent=KINDS.map(k=>{const m=snapshot.modules[k];return `${LABELS[k]} ${m.state==='complete'?'완료':m.state==='skipped'?'미실행':'미완료'}${m.reason?' ('+m.reason+')':''}`;}).join(' · ');$('summary').textContent=`선택 ${records.length}/${input.records.length}종${excluded.length?' · 미선택: '+excluded.join(', '):''}`;$('status').textContent=KINDS.some(k=>snapshot.modules[k].state==='limited')?'선택 범위의 일부 항목이 상한에 도달했습니다. 완료 항목과 미완료 사유를 확인하세요.':'선택 범위 분석을 완료했습니다.';kind=KINDS.find(k=>snapshot.modules[k].state==='complete')||'self';applyFilters();};worker.onerror=()=>{if(token===generation)showError('계산 중 오류가 발생했습니다. 이전 결과를 사용하지 않습니다.');};worker.postMessage({records,mode,options:opts});});
function filters(){for(const id of ['cutoff','poly-cutoff'])if($(id).validity.badInput)throw Error('유효한 cut-off 숫자를 입력하세요.');return {cutoff:parseCutoff($('cutoff').value),terminal:$('terminal').checked,polyCutoff:parseCutoff($('poly-cutoff').value)};}
function applyFilters(){if(!snapshot)return;clearCopyNotices();try{currentFilters=snapshot.mode==='thermo'?{}:filters();visible=filteredPairs(snapshot.pairs,currentFilters);$('filter-error').hidden=true;$('copy-all').disabled=false;$('save').disabled=false;listPage=0;structurePage=0;selected=null;setKind(kind);}catch(error){$('filter-error').textContent=error.message;$('filter-error').hidden=false;visible=[];selected=null;$('pair-list').replaceChildren();$('structures').replaceChildren();$('pair-title').textContent='표시 조건 확인 필요';$('pair-basis').textContent='';$('display-count').textContent='유효한 cut-off를 입력하세요.';for(const id of ['copy-all','copy-pair','save'])$(id).disabled=true;}}
for(const id of ['cutoff','terminal','poly-cutoff'])$(id).addEventListener('input',applyFilters);
$('all-dimers').addEventListener('click',()=>{$('cutoff').value='';$('terminal').checked=false;applyFilters();});$('recommended').addEventListener('click',()=>{$('cutoff').value='-9';$('terminal').checked=true;applyFilters();});$('all-poly').addEventListener('click',()=>{$('poly-cutoff').value='';applyFilters();});
function setKind(value){clearCopyNotices();kind=value;for(const k of KINDS){$('tab-'+k).setAttribute('aria-selected',String(k===kind));$('tab-'+k).tabIndex=k===kind?0:-1;}$('pair-panel').setAttribute('aria-labelledby','tab-'+kind);if(!snapshot)return;const list=visible.filter(p=>p.kind===kind);selected=list[0]||null;listPage=0;structurePage=0;renderList();renderDetail();}
for(const k of KINDS)$('tab-'+k).addEventListener('click',()=>setKind(k));
document.querySelector('.tabs').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const kinds=KINDS.filter(k=>!$('tab-'+k).hidden),i=kinds.indexOf(kind),next=event.key==='Home'?kinds[0]:event.key==='End'?kinds.at(-1):kinds[(i+(event.key==='ArrowLeft'?-1:1)+kinds.length)%kinds.length];setKind(next);$('tab-'+next).focus();});
function pager(id,page,total,size,change){const parent=$(id);parent.replaceChildren();if(total<=size)return;for(const [text,value] of [['이전',page-1],['다음',page+1]]){const b=el('button',text);b.type='button';b.disabled=value<0||value>=Math.ceil(total/size);b.addEventListener('click',()=>change(value));parent.append(b);}parent.append(el('span',`${page+1} / ${Math.ceil(total/size)} 페이지 · 전체 ${total.toLocaleString()}개`));}
function renderList(){const list=visible.filter(p=>p.kind===kind),all=snapshot.pairs.filter(p=>p.kind===kind),state=snapshot.modules[kind];$('pair-list').replaceChildren();$('metric-heading').textContent=snapshot.mode==='thermo'?'결합 bp':kind==='poly'?'최저 점수 합':'최저 ΔG';for(const p of list.slice(listPage*100,(listPage+1)*100)){const tr=el('tr',undefined,p===selected?'selected':''),td=el('td'),button=el('button',p.kind==='hetero'?`${p.first} × ${p.second}`:p.first,'pair-button');button.type='button';button.setAttribute('aria-current',String(p===selected));button.addEventListener('click',()=>{clearCopyNotices();selected=p;structurePage=0;renderList();renderDetail();});td.append(button);tr.append(td,el('td',`${p.structures.length}/${p.allStructures}`));const minimum=p.structures.length?p.structures.reduce((min,s)=>Math.min(min,kind==='poly'?s.scoreMicros:s.deltaGMicros),Infinity):null;tr.append(el('td',snapshot.mode==='thermo'?(p.structures.length?String(p.structures.reduce((max,s)=>Math.max(max,s.totalPairs),0)):'—'):minimum===null?'—':formatDG(minimum),kind!=='poly'&&snapshot.mode==='idt'&&isWarning(minimum)?'warning':''));$('pair-list').append(tr);}
 const a=all.reduce((n,p)=>n+p.structures.length,0),v=list.reduce((n,p)=>n+p.structures.length,0);$('display-count').textContent=`조합 표시 ${list.length}/${all.length} · ${kind==='poly'?'요약 후보':'구조'} 표시 ${v.toLocaleString()}/${a.toLocaleString()} · 숨김 ${(a-v).toLocaleString()}`;$('pair-note').textContent=state.state!=='complete'?`${LABELS[kind]} ${state.state==='skipped'?'미실행':'미완료'}: ${state.reason}`:!list.length?(a?'현재 표시 조건에 해당하는 결과 없음':all.length?(kind==='poly'?'이 후보 탐색 범위에서 비겹침 구간 조합 없음':'이 방식에서 검출 구조 없음'):'이 분석 범위의 조합 없음'):'조합을 선택하면 실제 서열과 결합을 볼 수 있습니다.';pager('list-pages',listPage,list.length,100,value=>{listPage=value;renderList();});}
function diagram(parent,lines){const pre=el('pre',lines.join('\n'),'diagram');pre.tabIndex=0;parent.append(pre);}
function renderDetail(){$('structures').replaceChildren();$('structure-pages').replaceChildren();$('copy-pair').disabled=!selected;if(!selected){$('pair-title').textContent='표시할 조합 없음';$('pair-basis').textContent='';return;}$('pair-title').textContent=selected.kind==='hetero'?`${selected.first} × ${selected.second}`:selected.first;$('pair-basis').textContent=kind==='poly'?'3가닥·두 비겹침 구간 후보 · 분류별 최저 점수 요약 · 실제 복합체 ΔG 아님':snapshot.mode==='thermo'?'Thermo optimal 3 원본 도식 · 실제 서열 확장 결과':`실제 서열쌍 ${num(selected.comparisons)}개 전수 분석 · 표시 조건에 해당한 구조 · ΔG 낮은 순`;
 if(!selected.structures.length){$('structures').append(el('p',kind==='poly'?'이 후보 탐색 범위에서 비겹침 구간 조합 없음':'이 방식에서 검출 구조 없음','empty'));return;}
 for(const [index,s] of selected.structures.slice(structurePage*50,(structurePage+1)*50).entries()){const n=structurePage*50+index+1,details=el('details',undefined,'structure'),summary=el('summary'),body=el('div',undefined,'structure-body');details.open=index===0;
  if(kind==='poly'){summary.textContent=`#${n} · ${s.category==='strong'?'각 구간 강함':'개별 약함/강약 혼합'} · 점수 합 ${formatDG(s.scoreMicros)}`;diagram(body,polyLines(s));body.append(el('p','같은 염기의 중복 점유 없음 · 실제 복합체 에너지는 계산하지 않음','note'));}
  else if(snapshot.mode==='thermo'){summary.textContent=`#${n} · 전체 상보 ${s.totalPairs} bp`;body.append(el('p',`실제 서열: ${s.variantFirst} / ${s.variantSecond}`,'structure-meta sequence-meta'));diagram(body,s.thermoDiagram);}
  else{const warning=isWarning(s.deltaGMicros),terminal=s.terminal.top>=3||s.terminal.bottom>=3;summary.append(el('span',`#${n} · ΔG ${formatDG(s.deltaGMicros)} kcal/mol`,warning?'warning':''));if(warning){summary.append(document.createTextNode(' '),el('span','경고','badge warning'));details.classList.add('warning-structure');}else if(terminal)summary.append(document.createTextNode(' '),el('span','3′ 말단 결합 주의','badge attention'));body.append(el('p',`실제 서열: ${s.variantFirst} / ${s.variantSecond}`,'structure-meta sequence-meta'),el('p',`3′ 말단 연속 결합: 상단 ${s.terminal.top} / 하단 ${s.terminal.bottom} bp · ΔG 구간 ${s.basePairs} bp`,'structure-meta'));diagram(body,s.diagram);}
  details.append(summary,body);$('structures').append(details);
 }pager('structure-pages',structurePage,selected.structures.length,50,value=>{structurePage=value;renderDetail();});}
function report(pairs){return textReport(snapshot.records,pairs,snapshot.mode,{...snapshot,filters:currentFilters});}
async function copy(pairs,id){
 if(!snapshot||!$('filter-error').hidden)return;const token=generation,epoch=copyEpoch,text=report(pairs);$('copy-status').textContent='';copyNotice(id,'복사 중…','pending');$(id).disabled=true;
 if(text.length>8000000){copyNotice(id,'결과가 큽니다. TXT 저장을 사용하세요.','error');$(id).disabled=false;return;}
 try{let rich=false;if(typeof ClipboardItem!=='undefined'&&navigator.clipboard?.write){const html=excelReport(snapshot.records,pairs,snapshot.mode,{...snapshot,filters:currentFilters});await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([text],{type:'text/plain'})})]);rich=true;}else await navigator.clipboard.writeText(text);
  if(token===generation&&epoch===copyEpoch){copyNotice(id,rich?'✓ 복사되었습니다.':'텍스트로 복사되었습니다.','success',true);if(!rich)$('copy-status').textContent='이 브라우저에서는 Excel용 글꼴 서식을 제공하지 못합니다.';}
 }catch{if(token===generation&&epoch===copyEpoch){copyNotice(id,'복사하지 못했습니다.','error');$('copy-status').textContent='클립보드를 사용할 수 없습니다. TXT 저장을 사용하세요.';}}
 finally{if(token===generation)$(id).disabled=!snapshot||!$('filter-error').hidden||(id==='copy-pair'&&!selected);}
}
$('copy-all').addEventListener('click',()=>snapshot&&copy(visible,'copy-all'));$('copy-pair').addEventListener('click',()=>selected&&copy([selected],'copy-pair'));$('save').addEventListener('click',()=>{if(!snapshot||!$('filter-error').hidden)return;const url=URL.createObjectURL(new Blob(['\uFEFF',report(visible)],{type:'text/plain;charset=utf-8'})),a=el('a');a.href=url;a.download=`oligo-${snapshot.mode}-${VERSION}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('copy-status').textContent='현재 표시 결과 TXT 저장을 요청했습니다.';});
$('mode-help').textContent=helpers[$('mode').value];
