import {calculate,adjusted,checkPipette,displayFormat,MASS_CONCENTRATION_UNITS,MASS_AMOUNT_UNITS,MOLAR_UNITS,COPY_CONCENTRATION_UNITS,COPY_AMOUNT_UNITS} from './core.mjs';
import {excelClipboard,nextComponentName} from './clipboard.mjs';
const $=id=>document.getElementById(id),f=displayFormat;let result=null,snapshot=null,rowCount=0;const counters={};let copying=false;let revision=0;
function cell(tr,value,tag='td'){const e=document.createElement(tag);e.textContent=value;tr.append(e);return e;}
function unitSelect(i,field){
 const select=document.createElement('select');select.dataset.field=field;select.setAttribute('aria-label',`${i}행 ${field==='targetUnit'?'목표':'Stock'} 단위`);
 const groups=field==='targetUnit'?[['반응당 copies',COPY_AMOUNT_UNITS],['반응당 질량',MASS_AMOUNT_UNITS],['질량 농도',MASS_CONCENTRATION_UNITS],['copies 농도',COPY_CONCENTRATION_UNITS],['몰농도',MOLAR_UNITS]]:[['질량 농도',MASS_CONCENTRATION_UNITS],['copies 농도',COPY_CONCENTRATION_UNITS],['몰농도',MOLAR_UNITS]];
 for(const [label,units] of groups){const group=document.createElement('optgroup');group.label=label;for(const unit of units){const option=document.createElement('option');option.value=unit;option.textContent=unit.replace('/rxn',' / 반응');group.append(option);}select.append(group);}
 select.value=field==='targetUnit'?'pg/rxn':'ng/µL';return select;
}
function copyBasis(i){
 const details=document.createElement('details');details.className='copy-basis';const summary=document.createElement('summary');summary.textContent='질량 ↔ copies 환산 정보';details.append(summary);
 const method=document.createElement('select');method.dataset.field='mwMethod';method.setAttribute('aria-label',`${i}행 copies 환산 방법`);
 for(const [value,text] of [['','방법 선택 (질량↔copies일 때 필수)'],['direct','분자량 직접 입력 (g/mol)'],['dsdna650','dsDNA 전체 길이 × 650 (근사)']]){const option=document.createElement('option');option.value=value;option.textContent=text;method.append(option);}details.append(method);
 for(const [field,label] of [['molecularWeight','전체 Plasmid 분자량 (g/mol)'],['lengthBp','전체 Plasmid 길이 (bp)']]){const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement('input');input.dataset.field=field;input.inputMode=field==='lengthBp'?'numeric':'decimal';input.autocomplete='off';input.setAttribute('aria-label',`${i}행 ${label}`);wrap.append(input);details.append(wrap);}
 const note=document.createElement('p');note.textContent='copies끼리는 입력 불필요. 길이는 insert/amplicon이 아닌 전체 Plasmid이며, 650은 dsDNA 근사값입니다.';details.append(note);return details;
}
function addRow(type){if(rowCount>=15)return;const generated=nextComponentName(type,counters,[...document.querySelectorAll('[data-field=name]')].map(el=>el.value));counters[type]=generated.count;const i=++rowCount,tr=document.createElement('tr');tr.dataset.type=type;
 for(const field of ['enabled','name','target','stock']){const td=document.createElement('td'),el=document.createElement('input');el.type=field==='enabled'?'checkbox':'text';el.dataset.field=field;el.setAttribute('aria-label',`${i}행 ${ {enabled:'계산에 포함',name:'Oligo 이름',target:'목표 최종 반응 농도 µM',stock:'Stock 농도 µM'}[field]}`);if(type==='Plasmid'&&(field==='target'||field==='stock'))el.setAttribute('aria-label',`${i}행 ${field==='target'?'목표 최종 농도 또는 반응당 양':'Stock 농도'}`);el.autocomplete='off';if(field==='enabled')el.checked=true;else if(field!=='name')el.inputMode='decimal';else {el.maxLength=100;el.value=generated.name;}td.append(el);if(type==='Plasmid'&&field==='name')td.append(copyBasis(i));if(field==='target'||field==='stock'){if(type==='Plasmid')td.append(unitSelect(i,field+'Unit'));else{const unit=document.createElement('span');unit.className='unit-label';unit.textContent='µM';td.append(unit);}}tr.append(td);} $('inputs').append(tr);for(const button of document.querySelectorAll('[data-add-type]'))button.disabled=rowCount>=15;$('row-count').textContent=`${rowCount} / 15개 성분`;}
function read(){return {reaction:$('reaction').value,mix:$('mix').value,count:$('count').value,rows:[...$('inputs').rows].map(tr=>({type:tr.dataset.type,...Object.fromEntries([...tr.querySelectorAll('input,select')].map(el=>[el.dataset.field,el.type==='checkbox'?el.checked:el.value]))}))};}
function invalidate(){revision++;$('copy-status').textContent='';if(result){result=null;snapshot=null;$('results').hidden=true;$('message').textContent='입력이 변경되었습니다. 이론 부피를 다시 계산하세요.';}for(const tr of $('inputs').rows)tr.classList.toggle('excluded',!tr.querySelector('input').checked);}
for(const button of document.querySelectorAll('[data-add-type]'))button.addEventListener('click',()=>{invalidate();addRow(button.dataset.addType);});$('mix-form').addEventListener('input',invalidate);
$('mix-form').addEventListener('submit',event=>{event.preventDefault();result=null;$('results').hidden=true;$('message').textContent='';try{snapshot=read();result=calculate(snapshot);render();}catch(error){snapshot=null;$('message').textContent=error.message;}});
function render(){const body=$('theory-body');body.replaceChildren();for(const r of result.rows){const tr=document.createElement('tr');[r.name,f(r.perReaction),f(r.batch),f(r.target)+' '+r.targetUnit,f(r.mixConcentration)+' '+r.mixUnit].forEach(v=>cell(tr,v));body.append(tr);}const te=document.createElement('tr');['TE',f(result.te),f(result.batchTE),'—','—'].forEach(v=>cell(te,v));body.append(te);$('summary').textContent=`최종 반응 ${f(result.reaction)} µL · Mix ${f(result.mix)} µL/반응 · ${result.count}반응 · 전체 Mix ${f(result.total)} µL. 이론 부피이며 분주 조정 미적용.`;const basisNotes=result.rows.filter(r=>r.conversionNote).map(r=>r.name+': '+r.conversionNote);if(basisNotes.length)$('summary').textContent+=' '+basisNotes.join(' / ');
 const ab=$('adjust-body');ab.replaceChildren();for(const [i,r] of [...result.rows,{name:'TE',batch:result.batchTE}].entries()){const tr=document.createElement('tr');cell(tr,r.name);cell(tr,f(r.batch));const td=cell(tr,''),el=document.createElement('input');el.type='text';el.inputMode='decimal';el.autocomplete='off';el.placeholder="실제 준비량 입력";el.setAttribute('aria-label',r.name+' 조정 전체량 µL');el.dataset.index=i;td.append(el);ab.append(tr);}clearAdjustment();$('results').hidden=false;$('message').textContent='이론 배합량을 계산했습니다.';}
function clearAdjustment(){$('adjust-status').textContent='';$('adjust-output').replaceChildren();}
$('pipette').addEventListener('input',clearAdjustment);
$('check-adjustment').addEventListener('click',()=>{clearAdjustment();if(!result)return;try{const inputs=[...$('adjust-body').querySelectorAll('input')],volumes=inputs.map(el=>el.value),settings={step:$('step').value,min:$('minimum').value,max:$('maximum').value};const a=adjusted(result,volumes.slice(0,-1),volumes.at(-1));const checks=volumes.map(v=>checkPipette(v,settings));const messages=checks.flatMap((c,i)=>c.valid?[]:[`${i===result.rows.length?'TE':result.rows[i].name}: ${c.note}`]);if(a.shortage)messages.push(`전체 Mix ${f(a.shortage)} µL 부족: 지정 반응 수를 준비할 수 없습니다.`);$('adjust-status').textContent=messages.join('\n');const out=$('adjust-output'),p=document.createElement('p');p.textContent=`실제 전체 Mix ${f(a.total)} µL · ${a.ready?'목표 전체량 충족':'준비량 부족'}. 간격·범위 충족은 장비 정확도 보증이 아닙니다.`;out.append(p);const table=document.createElement('table'),thead=document.createElement('thead'),head=document.createElement('tr');table.className='result-table';['Oligo','예상 최종 농도 / 반응당 양','목표 대비 편차 (%)'].forEach(v=>cell(head,v,'th'));thead.append(head);table.append(thead);const body=document.createElement('tbody');for(const r of a.rows){const tr=document.createElement('tr');[r.name,f(r.achieved)+' '+r.targetUnit,f(r.deviationPercent)].forEach(v=>cell(tr,v));body.append(tr);}table.append(body);const wrap=document.createElement('div');wrap.className='table-wrap';wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label','조정 후 예상 농도');wrap.append(table);out.append(wrap);}catch(error){$('adjust-status').textContent=error.message;}});
$('copy-excel').addEventListener('click',async()=>{
 if(!result||copying)return;
 const atRevision=revision,payload=excelClipboard(result);copying=true;$('copy-excel').disabled=true;$('copy-status').textContent='';
 try{
  if(!navigator.clipboard?.write||typeof ClipboardItem==='undefined')throw Error('이 브라우저는 서식 있는 복사를 지원하지 않습니다. Chrome의 HTTPS 또는 로컬 미리보기에서 실행하세요.');
  await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([payload.html],{type:'text/html'}),'text/plain':new Blob([payload.text],{type:'text/plain'})})]);
  if(atRevision!==revision)$('message').textContent='복사 중 입력이 변경되었습니다. 클립보드에는 변경 전 결과가 있습니다. 다시 계산 후 복사하세요.';
  $('copy-status').textContent=atRevision===revision?'복사했습니다. Excel의 A1 또는 빈 영역 시작 셀에 붙여넣고 원본 서식을 유지하세요. 맑은 고딕 9pt 표입니다.':'복사 중 입력이 변경되었습니다. 클립보드에는 변경 전 결과가 있습니다. 다시 계산 후 복사하세요.';
 }catch(error){$('copy-status').textContent='복사하지 못했습니다. '+(error.name==='NotAllowedError'?'브라우저의 클립보드 쓰기 권한을 확인하고 다시 누르세요.':error.message);}
 finally{copying=false;$('copy-excel').disabled=false;}
});
for(const type of ['F','R','P'])addRow(type);

