import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {compose} from '../../tools/dilution-calculator/composer-core.mjs';
const batch={volume:'1000',unit:'mL',fold:'1',solvent:'DW'},row={name:'試薬',target:'1',unit:'M',mode:'solid',mw:'153',stock:'',stockUnit:'M'};
let cases=0;const outputs=[];
function test(name,fn){fn();cases++;outputs.push(name);}
const run=(r={},b={})=>compose({...batch,...b},[{...row,...r}]);
test('user screenshot MW153 / 1M /1000uL no chemical form',()=>assert.equal(run({},{unit:'uL'}).rows[0].amount,'0.153 g'));
test('1L1M userMW153',()=>assert.equal(run().rows[0].amount,'153 g'));
test('10X doubles actual target and amount correctly',()=>{const x=run({target:'10',unit:'mM',mw:'121.14'},{fold:'10'});assert.equal(x.rows[0].amount,'12.114 g');assert.equal(x.rows[0].actual,'100 mM');});
test('mass percent noMW',()=>assert.equal(run({target:'1',unit:'%w/v',mw:''}).rows[0].amount,'10 g'));
test('mass mg/L source PBS',()=>assert.equal(run({target:'795',unit:'mg/L',mw:''}).rows[0].amount,'0.795 g'));
test('pure liquid percent',()=>assert.equal(run({mode:'pure',target:'15',unit:'%v/v',mw:''}).rows[0].amount,'150 mL'));
test('NEB Tween0.1%1L10X',()=>assert.equal(run({mode:'pure',target:'0.1',unit:'%v/v',mw:''},{fold:'10'}).rows[0].amount,'10 mL'));
test('Stock1M to10mM10X1L',()=>assert.equal(run({mode:'stock',target:'10',unit:'mM',stock:'1',stockUnit:'M',mw:''},{fold:'10'}).rows[0].amount,'100 mL'));
test('percentStock10%to1%',()=>assert.equal(run({mode:'stock',target:'1',unit:'%w/v',stock:'10',stockUnit:'%w/v',mw:''}).rows[0].amount,'100 mL'));
test('composite10X stock1X',()=>assert.equal(run({mode:'stock',target:'1',unit:'X',stock:'10',stockUnit:'X',mw:''}).rows[0].amount,'100 mL'));
test('100Xstockto10X250uL',()=>assert.equal(run({mode:'stock',target:'1',unit:'X',stock:'100',stockUnit:'X',mw:''},{volume:'250',unit:'uL',fold:'10'}).rows[0].amount,'25 uL'));
test('molar to massStock conversion',()=>assert.equal(run({mode:'stock',target:'1',unit:'mM',mw:'40',stock:'4',stockUnit:'mg/mL'}).rows[0].amount,'10 mL'));
test('mass to molarStock conversion',()=>assert.equal(run({mode:'stock',target:'4',unit:'mg/L',mw:'40',stock:'1',stockUnit:'mM'}).rows[0].amount,'100 mL'));
test('explicit zero solid needsnoMW',()=>assert.equal(run({target:'0',mw:''}).rows[0].amount,'0 g'));
test('blank target neverzero',()=>assert.equal(run({target:''}).complete,false));
test('missingMW rowvisibleerror',()=>assert.match(run({mw:''}).rows[0].error,/MW/));
test('missingStock visibleerror',()=>assert.match(run({mode:'stock',stock:''}).rows[0].error,/Stock/));
test('negative target rejected',()=>assert.equal(run({target:'-1'}).complete,false));
test('zero stock rejected',()=>assert.equal(run({mode:'stock',stock:'0'}).complete,false));
test('stock less than made concentration rejected',()=>assert.equal(run({mode:'stock',stock:'.5'}).complete,false));
test('percentvv at10X impossible',()=>assert.equal(run({mode:'pure',target:'15',unit:'%v/v'},{fold:'10'}).complete,false));
test('liquid volume sum rejected',()=>{const r={...row,mode:'stock',target:'0.6',stock:'1'};assert.match(compose(batch,[r,r]).errors.join(),/使用量|사용량/);});
test('vv sum rejected',()=>{const r={...row,mode:'pure',target:'60',unit:'%v/v'};assert.equal(compose(batch,[r,r]).complete,false);});
test('zero final volume rejected',()=>assert.equal(run({},{volume:'0'}).complete,false));
test('empty rows rejected',()=>assert.equal(compose(batch,[]).complete,false));
test('wrong dimensions rejected',()=>assert.equal(run({mode:'stock',unit:'X',stock:'10',stockUnit:'M'}).complete,false));
test('scientific small amount exact',()=>{const x=run({target:'1e-9',mw:'40'},{volume:'1',unit:'uL'});assert.deepEqual(x.rows[0].exact,{n:'1',d:'25000000000000',unit:'g'});});
test('q.s never estimateswater volume',()=>assert.equal(run().makeup,'DW로 최종 1000 mL까지 맞추세요.'));
test('customsolvent instruction',()=>assert.match(run({},{solvent:'TE'}).makeup,/^TE로/));
const presets=JSON.parse(readFileSync(new URL('../../tools/dilution-calculator/presets.json',import.meta.url))).recipes;
for(const p of presets)test('curated preset arithmetic '+p.id,()=>{const rows=p.rows.map(r=>({...r,mw:'100',stock:r.unit==='%v/v'?'100':'1000',stockUnit:r.unit}));const x=compose(batch,rows);assert.equal(x.complete,true,p.id+JSON.stringify(x));assert.equal(x.rows.length,p.rows.length);});
console.log(cases+' engine cases passed');
